# Generated by Django 3.0.3 on 2020-05-18 17:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hill', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='hillprogram',
            name='content',
            field=models.TextField(default=''),
            preserve_default=False,
        ),
    ]
